### ISSUE TITLE
No Vita FW 3.65/3.67 Support

### ISSUE THREAD

**Issue by cainan-c** [xerpi/ds4vita#35]
Hey if possible please update this plugin to support enso on 3.65

**Comment by xerpi** [comment]
Hi, I guess that the problem is when trying to pair a new controller? And if you already have the controller paired (from 3.60) then it works fine?

**Comment by lufyhus** [comment]
helll xerpi,i love ds3vita/ds4vita so much. Theflow released Enso 3.65 (update from 3.60) but i don't update yet because i don't know your plugin which support fw 3.65 or not? If not, can you port your plugin for fw 3.65, thank you so much. Please reply me soon and hope you understand what i say because my english is so bad

**Comment by Dunstans** [comment]
Hi xerpi, the problem persists even when it is a linked control in version 3.60, when going to 3.65 it stopped working completely.

**Comment by ness151** [comment]
Going to chime in here and say that I can't even get it to connect.  Using a non-slim, 1st party controller.  It sees the controller, but never connects.

**Comment by YobaHere** [comment]
I had controller paired on 3.60 enso, then updated my Vita to 3.65 enso and now i can’t pair it again, there is a DUALSHOCK(tm)4 controller on list, but when i pressins ps button on ds4 its detected as nameless device on list

**Comment by cainan-c** [comment]
Was just using the tai config from another place not ur0 where the plugin was. Only recently found this out
